### ISSUE TITLE
Don't insert pair when there is text immediately after the cursor

### ISSUE THREAD

**Issue by comfortablynick** [ZhiyuanLck/smart-pairs#1]
Hi, 

Thanks for the plugin! This behavior doesn't seem ideal; usually, you don't intend to insert a pair in this situation.

[Here is a screen recording](https://asciinema.org/a/bI1z4gzntnCO6F0ehlgIcLk74)

**Comment by ZhiyuanLck** [comment]
This can be done with an `ignore_after` option，I will add it later.
