### ISSUE TITLE
Pressing backspace at start of buffer throws error

### ISSUE THREAD

**Issue by ajitid** [ZhiyuanLck/smart-pairs#10]
**To reproduce**

1. Open a new buffer
1. Go to insert mode and start pressing backspace

You would see:

![image](https://user-images.githubusercontent.com/26769888/154640913-34d929cc-3040-4668-94e1-a4f44572dfb1.png)

**Comment by ZhiyuanLck** [comment]
It has been fixed in the commit to be pushed. :) 
For some network issues, it will be pushed after several hours, which comes with the real multiline pair support.

**Comment by ajitid** [comment]
Oh okay! Quick ques, would real multiline pair also solve this issue:

![anim-rg](https://user-images.githubusercontent.com/26769888/154691803-a58c582c-5937-43c0-ba57-86f3587c76f1.gif)

^ _Pressing backspace also pulls in the bracket to the above line_

Or is there a separate setting to configure it?

**Comment by ZhiyuanLck** [comment]
Did you mean that you do not want the mart deletion of the empty line of such cases?
```
text {
  |
}
======
text {|}

**Comment by ajitid** [comment]
Kind of. I don't want this behavior if I already have some text in b/w pairs (in this case we have text at line 37)

**Comment by ZhiyuanLck** [comment]
Ok, I'll add an option later.
