### ISSUE TITLE
Smart deletion only if there is not content between pairs

### ISSUE THREAD

**Issue by ajitid** [ZhiyuanLck/smart-pairs#11]
_Thought to create an issue to separately [track its progress](https://github.com/ZhiyuanLck/smart-pairs/issues/10#issuecomment-1044533594)_

Here, I'm pressing backspace. which also pulls in closing pair to the line above:

![anim-rg](https://user-images.githubusercontent.com/26769888/154696623-1d260acf-1ec4-44df-918a-1ea9e437ca85.gif)

Though it is favorable in the case when opening pair is just above the cursor:

![anim-rg](https://user-images.githubusercontent.com/26769888/154699932-8ada6a32-637f-4d58-bf0c-3825822589ba.gif)

We think the plugin could be even smarter here and do smart deletion **only when** opening pair lies above cursor line.

**Comment by ZhiyuanLck** [comment]
All multiline deletion behaviors can be configured now. It may need some time to setup your own options. Please refer to the [document](https://github.com/ZhiyuanLck/smart-pairs/blob/master/doc/delete.md) for details.

**Comment by ajitid** [comment]
Thanks @ZhiyuanLck!


For future devs who would stumble upon this issue, the following setting resolves issue shown in first GIF (but results in duplicating the same behavior for the latter one):

```lua
  delete = {
    empty_line = {
      text_bracket = {
        one = {
          strategy = 'leave_zero_above',
        },
      }
    }
  }
```
