### ISSUE TITLE
Plugin overrides Vim's backspace behavior if cursor is on the following line of opening pair 

### ISSUE THREAD

**Issue by ajitid** [ZhiyuanLck/smart-pairs#12]
Here's an issue I encountered:

![anim-rg](https://user-images.githubusercontent.com/26769888/154706394-aabe7f15-7b0d-4a4e-957b-f16c0a08ac41.gif)

When a line is empty:
- pressing backspace in the first example clears out tab spaces first and then the cursor moves to "first line", which is correct behavior
- while in the second example, it pulls "second line" above. This happened because the cursor was in the line right after opening brace one. This isn't Vim's default behavior

**Comment by ZhiyuanLck** [comment]
Well, it is my fault that I usually use `<m-O>` to start a new line above in the insert mode. I will correct this behavior.

**Comment by ajitid** [comment]
Actually an easier way to reproduce it is to type enter many times in a buffer and hit backspace just once:

![anim-rg](https://user-images.githubusercontent.com/26769888/154790177-56087dbd-e315-45d8-ae42-8e7e1b19c96d.gif)

With this, I think  the ticket should change to a bug.

**Comment by ZhiyuanLck** [comment]
@ajitid in fact it is not a bug, smart deletion allow you to quickly delete all blanks at end of file. In the next commit, you can control all these default behaviors. I provide plenty of smart actions/strategies that can apply to 18 different cases when you want to do a deletion on an empty line. This work has almost been done and will come soon.
