### ISSUE TITLE
Work together with nvim-cmp

### ISSUE THREAD

**Issue by bellini666** [ZhiyuanLck/smart-pairs#2]
Hi,

First of all, nice plugin!

Using this plugin I can no longer confirm a completion using `nvim-cmp` with `<cr>`.

Also, it would be nice if this plugin can work together with it by automatically adding `(|)` when completing a function, just like https://github.com/windwp/nvim-autopairs does when you configure cmp to use it.

**Comment by ZhiyuanLck** [comment]
For `nvim-cmp`, maybe you can try the following config:
```lua
['<CR>'] = function()
  cmp.mapping.confirm({ select = true })()
  require('pairs'):type_enter()
end
```
If this not work, please inform me.

Cause I am not familiar with `nvim-cmp`，you can try yourself first with its interface. I will add the description about the interfaces of `smart-pairs` later in the readme. They are simple:

- `require('pairs'):typeset_left(left)`
- `require('pairs'):typeset_right(right)`
- `require('pairs'):typeset_del()`
- `require('pairs'):typeset_enter()`
- `require('pairs'):typeset_space()`

Integration with completion plugin will be considered later.

**Comment by karlc1** [comment]
I have this same issue, and your fix does not work. This really makes this otherwise nice plugin unusable for me. 
If you allow to pass a function to enable_enter, maybe something like this could work:

```
enable_enter = function()
    return require("cmp").visible() == false
end
```

This would support other cases where you don't want the <cr> behaviour to trigger.

**Comment by ZhiyuanLck** [comment]
@karlc1 you are right. There should be three things to do in the next commit

1. Make all enable options be a boolean value or a function that return a boolean value. 
2. Add custom fallback function when enable option is set to false
3. Add extra before and after hook

**Comment by ZhiyuanLck** [comment]
If `enable_cond` and `enable_fallback` options can be used to work with `nvim-cmp`, I'm glad to post your config in readme to help the other one.

**Comment by ZhiyuanLck** [comment]
@bellini666 @karlc1  A minial workaround config about pairs completion after function may be
```
local cmp = require('cmp')
local k = cmp.lsp.CompletionItemKind

cmp.event:on('confirm_done', function(event)
  local kind = event.entry:get_completion_item().kind
  if kind == k.Method or kind == k.Function then
    require('pairs.bracket').type_left('(')
  end
end)
```
But I do not check if it works.

**Comment by bellini666** [comment]
Hey @ZhiyuanLck ,

I could not make that with `enable_cond`, but I ended up doing the following:
```lua
use({
  "ZhiyuanLck/smart-pairs",
  config = function()
    require("pairs"):setup({
      enter = {
        enable_mapping = false,
      },
    })
  end,
}),
```

Then on cmp setup:
```lua
local cmp = require("cmp")
local kind = cmp.lsp.CompletionItemKind

cmp.setup({
  mapping = {
    ["<CR>"] = cmp.mapping(function(fallback)
      if not cmp.confirm({ select = false }) then
        require("pairs.enter").type()
      end
    end),
  },
})
cmp.event:on("confirm_done", function(event)
  local item = event.entry:get_completion_item()
  local parensDisabled = item.data and item.data.funcParensDisabled or false
  if not parensDisabled and (item.kind == kind.Method or item.kind == kind.Function) then
    require("pairs.bracket").type_left("(")
  end
end)
```

(note: the `parensDisabled` avoids adding "(" after completing an import of a function)

With that config, smart-pairs and cmp are working together nicely!

**Comment by ZhiyuanLck** [comment]
Glad to see your solution! I'll close this issue and link your comment as a temporary workaround.

**Comment by marcelarie** [comment]
idk if I'm doing something wrong but with the workaround does not work for me. When I want to select the first match from `cmp` it just enters.

**Comment by ajitid** [comment]
@marcelarie under <CR> mapping, try `select = true`

**Comment by marcelarie** [comment]
Me too.

**Comment by roginfarrer** [comment]
I will open a new issue now, I thought it helpful to consolidate concerns with cmp to one place. Thanks!

**Comment by ajitid** [comment]
@bellini666 — which langserver sends `item.data.funcParensDisabled`? I tried two (tsserver and gopls) and they don't send it.

@marcelarie — assuming what you want is typing few chars and hit enter (rather than manually selecting the first item using `<c-n>`), then yes, using `select=true` would help.

**Comment by marcelarie** [comment]
@ajitid yes I tried that but it does nothing, can't select the first item or add a new line on enter with [this](https://github.com/ZhiyuanLck/smart-pairs/issues/2#issuecomment-1037232219) config.

**Comment by ajitid** [comment]
@marcelarie it should be `cmp.confirm` not `cmp.mapping.confim`

**Comment by marcelarie** [comment]
idk how I did not see that. thanks @ajitid !!

**Comment by bellini666** [comment]
> @bellini666 — which langserver sends `item.data.funcParensDisabled`? I tried two (tsserver and gopls) and they don't send it.

Pyright sends it. Don't know if it is something specific or part of the language server spec (thought it was)
