### ISSUE TITLE
E5108: Attempt to index local 'right' (a nil value)

### ISSUE THREAD

**Issue by roginfarrer** [ZhiyuanLck/smart-pairs#21]
I got this error in a markdown file while inside a `[]` pair inside a backticked codeblock:

```
E5108: Error executing lua ...m/site/pack/packer/start/smart-pairs/lua/pairs/enter.lua:38: attempt to index local 'right' (a nil value)
stack traceback:
	...m/site/pack/packer/start/smart-pairs/lua/pairs/enter.lua:38: in function 'type_aux'
	...m/site/pack/packer/start/smart-pairs/lua/pairs/enter.lua:56: in function 'type'
	/Users/rfarrer/.config/nvim/lua/user/plugins/cmp.lua:40: in function 'on_keymap'
	...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:144: in function 'callback'
	...site/pack/packer/start/nvim-cmp/lua/cmp/utils/keymap.lua:112: in function <...site/pack/packer/start/nvim-cmp/lua/cmp/utils/keymap.lua:108>
	...site/pack/packer/start/nvim-cmp/lua/cmp/utils/keymap.lua:242: in function <...site/pack/packer/start/nvim-cmp/lua/cmp/utils/keymap.lua:241>
```

**Comment by ZhiyuanLck** [comment]
It should be fixed in the [latest commit](https://github.com/ZhiyuanLck/smart-pairs/commit/878db6a4273bbbf3f398702d23c574c2e62ed397)

**Comment by smjonas** [comment]
This issue occurs again now (I think it's a regression) when pressing Enter in insert mode with a buffer that has the following contents (`|` is the cursor position):
```
(|
```
Could you please confim it and reopen this issue?

**Comment by ZhiyuanLck** [comment]
@smjonas I create an empty buffer that only contains the line of `(|` and press `<cr>`, but everything is normal. Are you sure that you have updated to the latest version of the plugin or you are missing some other information. It will be better if you show you plugin config.

**Comment by smjonas** [comment]
Yes sorry, it is fixed now, I used an old version.
