### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by bryant-the-coder** [ZhiyuanLck/smart-pairs#27]
https://user-images.githubusercontent.com/92417638/155437952-b6937792-3a4b-42de-b1ab-0270667d8e87.mp4

@ZhiyuanLck Please see this vid. It shows the bug. I dont know if i setup wrongly or not. [My cmp setup](http://0x0.st/oK2s.txt)

**Comment by bryant-the-coder** [comment]
![image](https://user-images.githubusercontent.com/92417638/155438332-d7589173-36cc-48d6-a27d-1ab9eb7e1f3f.png)

**Comment by bryant-the-coder** [comment]
i dont know what i am doing wrong

**Comment by ZhiyuanLck** [comment]
First check if there is a single `)` in the rest of you file. And in your second screenshot, does it the same issue as the previous one? If not, please create a new issue and detail the steps to produce.

**Comment by bryant-the-coder** [comment]
It is related

**Comment by ZhiyuanLck** [comment]
When there is an extra right bracket detected below your current line (according the value of `max_search_lines`), then the `)` will not be completed. For now, the plugin is still in develop and the brackets in comment and for example in lua strings of the format 
 `[[]]` are not correctly processed.

And I still don't know how the error you show is generated. Can you provide detailed steps to produce?

**Comment by bryant-the-coder** [comment]
Hmm it is all after i added the cmp thing into my cmp.lua

**Comment by ZhiyuanLck** [comment]
I did find a bug, but I am not sure if it is related.

**Comment by bryant-the-coder** [comment]
oh ok... i will report more xD

**Comment by bryant-the-coder** [comment]
@ZhiyuanLck now i cant seem to enter to complete completion

**Comment by ZhiyuanLck** [comment]
You create a new one, so is the issue here solve?

**Comment by bryant-the-coder** [comment]
i will close it thanks. Btw good plugin
