### ISSUE TITLE
Smart delete issues with indentation

### ISSUE THREAD

**Issue by bellini666** [ZhiyuanLck/smart-pairs#4]
Consider the following:

```python
if True:
    if True:
        pass
    |
```

My cursor is at `|`. If I press backspace to reduce the indentation level it removes the whole line and I end up with:

```python
if True:
    if True:
        pass|
```

**Comment by ZhiyuanLck** [comment]
Well it seems that the indent rule should be more intelligent :)

For now you can set `delete.empty_line.trigger_indent.text` to `-100` or set `delete.empty_line.enable_oneline` to `false`. as a workaround.

If there is not good solution, I will remove this feature or make it untenabled by default.

**Comment by ZhiyuanLck** [comment]
It should be normal now.
